CHAT_HOST = 'HOST'
CHAT_PORT = 'PORT'
FILE_PATH = 'FILE_PATH'
CHAT_USER_NAME = 'USER_NAME'
CHAT_MESSAGE = 'MESSAGE'
CHAT_TOKEN = '298afda2-30a7-11eb-8c47-0242ac110002'

app_config = {CHAT_HOST: 'minechat.dvmn.org', CHAT_PORT: 5000, FILE_PATH: 'minechat.history'}
